In [1]:
import random

import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.svm import LinearSVC
from sklearn.svm import SVC
from sklearn import metrics
from sklearn.metrics import classification_report



random.seed()

In [2]:
df = pd.read_csv('../data/iris.csv')
df['class'] = np.where(df["class"]=="setosa",0,
                            np.where(df["class"]=="versicolor",1,2))

df

sepal_length  sepal_width  petal_length  petal_width  class
0             5.1          3.5           1.4          0.2      0
1             4.9          3.0           1.4          0.2      0
2             4.7          3.2           1.3          0.2      0
3             4.6          3.1           1.5          0.2      0
4             5.0          3.6           1.4          0.2      0
..            ...          ...           ...          ...    ...
145           6.7          3.0           5.2          2.3      2
146           6.3          2.5           5.0          1.9      2
147           6.5          3.0           5.2          2.0      2
148           6.2          3.4           5.4          2.3      2
149           5.9          3.0           5.1          1.8      2

[150 rows x 5 columns]

In [3]:
independent_variables = df.drop('class', axis=1)
x = independent_variables.values
y = df['class'].values

x_train, x_test, y_train, y_test = train_test_split(x, y, train_size = 0.8, test_size = 0.2, random_state = random.randrange(99999), shuffle = True)

svc = LinearSVC(max_iter=5000)
# svc = SVC(max_iter=5000, kernel='linear')
svc.fit(x_train, y_train)
y_pred_train = svc.predict(x_train)
y_pred_test = svc.predict(x_test)

print('Training Accuracy {}'.format(metrics.accuracy_score(y_train, y_pred_train)))

Training Accuracy 0.9833333333333333


In [4]:
print('Training Confusion = \n{}'.format(metrics.confusion_matrix(y_train, y_pred_train, labels=[0,1,2])))

Training Confusion = 
[[40  0  0]
 [ 0 37  2]
 [ 0  0 41]]


In [5]:
print(classification_report(y_train, y_pred_train))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        40
           1       1.00      0.95      0.97        39
           2       0.95      1.00      0.98        41

    accuracy                           0.98       120
   macro avg       0.98      0.98      0.98       120
weighted avg       0.98      0.98      0.98       120



In [6]:
print('Test Accuracy {}'.format(metrics.accuracy_score(y_test, y_pred_test)))

Test Accuracy 0.9333333333333333


In [7]:
print('Test Confusion = \n{}'.format(metrics.confusion_matrix(y_test, y_pred_test, labels=[0,1,2])))

Test Confusion = 
[[10  0  0]
 [ 0 10  1]
 [ 0  1  8]]


In [8]:
print(classification_report(y_test, y_pred_test))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       0.91      0.91      0.91        11
           2       0.89      0.89      0.89         9

    accuracy                           0.93        30
   macro avg       0.93      0.93      0.93        30
weighted avg       0.93      0.93      0.93        30

